version: '2'
services:
  avatica:
    ports:
      - "8765:8765"
    links:
      - postgresql
    image: joshelser/avatica-postgresql-server
    command: "-u 'jdbc:postgresql://postgresql:5432/avatica' -p 8765"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:9.6
    ports:
      # Default port for the docker image
      - "5432:5432"
    environment:
      POSTGRES_DB: avatica
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
